### PR TITLE
Add Teal Capabilities

### PR DESCRIPTION
**Pull request by tooolbox**
This PR adds [Teal](https://github.com/teal-language/tl) support to Algernon, as per #58 

- On startup, loads Teal as well as other required Lua modules into the VM
- Recognizes the `.tl` extension for scripts and executes them
- Looks for `index.tl` as a directory index file

I realized, in the course of adding these features, it complicated the implementation to put them behind a feature flag, and also didn't match Algernon's ethos of "everything and the kitchen sink".  So, it's just a straightforward feature add.

I noted that the builtin Lua function `error()` has been overwritten by Algernon, which I think is not ideal and perhaps should be reverted, (what if you use a module that calls it?) but in the meantime I renamed it to `throw()`.

Currently there's no caching in production mode.  The reasons are twofold: I don't really personally need it at the moment, and I realize it's also rather complicated because the first request compiles and saves to disk, and subsequent requests hit disk, with the appropriate per-file mutex behavior.  I don't know @xyproto if you want to take that on since you're more familiar with the codebase, or if not, perhaps you can give suggestions on the best way to implement.  But generally, I'm inclined to make the whole caching functionality a separate PR.

Currently, `data.tl` is not supported, nor `serverconf.tl` or anything else, just Teal handler files.  I'm not sure how vital those are and if they can simply be added down the road.

### CODE REVIEW

**Comment by tooolbox** [comment]
I did some more local testing, converting a fairly large Lua file to Teal and then getting rid of all errors.  This is pretty legit.

I may, however, want to handle the caching-in-prod issue.  It's plenty fast, but any time the page hiccups I will wonder if it's because of Teal, so I will probably add the caching just to take that off my mind.

**Comment by tooolbox** [comment]
Have an idea on a simple way to handle caching, will get that added shortly.

In the meantime it looks like [someone patched Teal](https://github.com/teal-language/tl/pull/523) to get around the bug in Gopher-Lua, so I can revert to the original version.

Also, there's [no progress](https://github.com/yuin/gopher-lua/issues/336) on the lack of `string.dump` in Gopher-Lua, which is why I had to patch `compat52`, but I realize that I could probably patch that within Algernon itself.  Then I will have zero forked Lua libraries, which is the ideal number.

**Comment by tooolbox** [comment]
Alright, using latest Teal now and things seem fine.  I'm not going to mess with `compat52` at the moment.  @xyproto this is good to go if you want to take it for a spin.  Interested in your feedback!

**Comment by tooolbox** [comment]
Interesting.  I thought I was loading Teal at the correct point, but I found in testing that I was incorrect and if the luapool grew, it could result in a LState without Teal loaded and subsequent sadness.

Per the [LState pool pattern](https://github.com/yuin/gopher-lua#the-lstate-pool-pattern) that correct point to configure the environment is in the New() call, so I'm doing it there.  Feedback welcome.

**Comment by xyproto** [comment]
Thanks for creating the PR, it looks excellent! I'll give it a spin tomorrow before merging. 👍

**Comment by xyproto** [comment]
Merged, thanks!

Algernon compiled and ran great here, and the code looks good to me, but I did not find a good way to test the Teal capabilities.

Do you happen to have a sample `index.tl` file, just for quickly trying out Teal?

**Comment by tooolbox** [comment]
Sure!

```lua
function add(a: number, b: number): number
    return a+b
end

print(add(1, 2))
```

Perhaps I'll add it as an example.

**Pull request merged**
