### PR TITLE
Improved MSSQL Support

### PR DESCRIPTION
**Pull request by tooolbox**
- Adds the ability to pass a table as the 3rd argument of `MSSQL()` which can be ordinal or named parameters.
- Results are placed into a two-dimensional table.
- Results are transformed into appropriate Lua types.

Still testing this, so not quite ready yet.  Will fix most of what's brought up in #57

### CODE REVIEW

**Comment by tooolbox** [comment]
Okay great, so now you can do:

```lua
local results = MSSQL("SELECT a, b FROM c WHERE d = @foo", connstring, {foo = "bar"})
local row = results[1]
local a = row["a"]
```

Still have the issue of result sets sorting incorrectly in pongo2 templates due to stringified numeric keys, but everything else is working.  No idea why tests are failing.

**Comment by tooolbox** [comment]
Any thoughts @xyproto ?

**Comment by tooolbox** [comment]
Awesome, thank you.  I saw the gluamapper PR was merged as well.  Now I can follow up with a PR to fix the JSON output, which completes the ability to execute a query on the DB and dump the result set as JSON.  :+1:

**Comment by xyproto** [comment]
Thank you for the contributions!

**Pull request merged**
